NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.scrapper.vt.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.scrapper.vt.com-cert.pem
    OrganizationalUnitIdentifier: peer
